- hosts: windows
  tasks:
      - name: Install Cygwin 2.10.0
        win_chocolatey:
          name: cygwin
          version: "2.10.0"
      - name: Install WGet with source Cygwin
        win_chocolatey:
          name: wget
          source: cygwin
      - name: Install SSH with source Cygwin
        win_chocolatey:
          name: ssh
          source: cygwin
      - name: Install OpenSSH with source Cygwin
        win_chocolatey:
          name: openssh
          source: cygwin